version: 2

updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      time: '09:00'
      timezone: "Europe/London"
    commit-message:
      prefix: '⬆️'
      include: 'scope'
    open-pull-requests-limit: 5
    versioning-strategy: increase

  - package-ecosystem: "github-actions"
    directory: "./github/workflows"
    schedule:
      interval: "weekly"
      time: '09:00'
      timezone: "Europe/London"
    commit-message:
      prefix: '⬆️'
      include: 'scope'
    open-pull-requests-limit: 5